plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/mmm/桌面/Shensist_Matrix/I_Want_It_Agent"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]